apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-unique
  labels:
    workflows.argoproj.io/achieve-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is simple, from sosotech
      You can do it too
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay
      command: ["cowsay"]
      args: ["hello Sosotech"]
